/* Autogenerated by png2wx.pl on Fri Nov 14 17:47:25 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_logimg_C;
extern wxBitmap *_img_logimg_E;
extern wxBitmap *_img_logimg_NE;
extern wxBitmap *_img_logimg_N;
extern wxBitmap *_img_logimg_NW;
extern wxBitmap *_img_logimg_SE;
extern wxBitmap *_img_logimg_S;
extern wxBitmap *_img_logimg_SW;
extern wxBitmap *_img_logimg_U;
extern wxBitmap *_img_logimg_W;

#endif /* ICONS_H */
